"""Cover Letter PDF Generator (H-02).

Generates a WeasyPrint PDF cover letter for IFNS submission under ст. 219 НК РФ.

The letter contains:
  - Addressee block (tax authority — blank field for user to fill)
  - Applicant: ФИО, ИНН, address (placeholder)
  - Statement text referencing ст. 219 НК РФ
  - List of attached documents (N receipts, M prescriptions, PDF registry)
  - Date and signature line

Fallback: if WeasyPrint is not installed, returns a minimal plaintext-inside-PDF
generated by reportlab (if available), so the ZIP always contains some cover letter.
"""
from __future__ import annotations

import logging
import uuid
from decimal import Decimal
from typing import Any

logger = logging.getLogger(__name__)

# ── WeasyPrint ────────────────────────────────────────────────────────────────
try:
    from weasyprint import HTML as _WP_HTML

    _HAS_WEASYPRINT = True
except ImportError:
    _HAS_WEASYPRINT = False

# ── ReportLab fallback ────────────────────────────────────────────────────────
try:
    import io as _io

    from reportlab.lib.pagesizes import A4 as _A4
    from reportlab.lib.styles import getSampleStyleSheet as _get_styles
    from reportlab.lib.units import cm as _cm
    from reportlab.pdfbase import pdfmetrics as _pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont as _TTFont
    from reportlab.platypus import (
        Paragraph as _Para,
        SimpleDocTemplate as _Doc,
        Spacer as _Spacer,
    )

    _HAS_REPORTLAB = True
except ImportError:
    _HAS_REPORTLAB = False


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<style>
  @page {{ size: A4; margin: 2cm 2.5cm 2cm 3cm; }}
  body {{
    font-family: "DejaVu Sans", Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #000;
  }}
  .addressee {{
    float: right;
    width: 55%;
    margin-bottom: 4em;
    font-size: 10pt;
  }}
  .addressee p {{ margin: 0; }}
  .clearfix::after {{ content: ""; display: table; clear: both; }}
  h1 {{
    text-align: center;
    font-size: 13pt;
    font-weight: bold;
    margin: 1em 0 0.5em 0;
  }}
  .body-text {{ text-align: justify; margin: 1em 0; }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 1em 0;
    font-size: 10pt;
  }}
  td {{ padding: 4px 8px; }}
  td:first-child {{ width: 30px; text-align: right; }}
  .footer {{ margin-top: 3em; font-size: 10pt; }}
  .footer .line {{ margin-top: 1em; }}
  .blank {{ border-bottom: 1px solid #000; display: inline-block; min-width: 200px; }}
</style>
</head>
<body>

<div class="clearfix">
  <div class="addressee">
    <p>В ИФНС России №____</p>
    <p>по г. _____________________</p>
    <p>&nbsp;</p>
    <p>от <span class="blank">{full_name}</span></p>
    <p>ИНН: <span class="blank">{inn}</span></p>
    <p>Адрес: <span class="blank">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </div>
</div>

<h1>ЗАЯВЛЕНИЕ</h1>
<h1>о предоставлении социального налогового вычета</h1>

<p class="body-text">
  В соответствии с подпунктом 3 пункта 1 и пунктом 2 статьи 219 Налогового
  кодекса Российской Федерации прошу предоставить мне социальный налоговый вычет
  по расходам на приобретение лекарственных препаратов за <strong>{year} год</strong>.
</p>

<p class="body-text">
  Сумма расходов на лекарственные препараты, назначенные лечащим врачом,
  составила <strong>{total_amount} ₽</strong>.
  Сумма к возврату НДФЛ (13%) составляет <strong>{ndfl_return} ₽</strong>.
</p>

<p class="body-text">
  К настоящему заявлению прилагаются следующие документы:
</p>

<table>
  {doc_rows}
</table>

<p class="body-text">
  Прошу перечислить суммы налогового вычета на расчётный счёт
  (реквизиты прилагаются) либо зачесть в счёт предстоящих налоговых платежей.
</p>

<div class="footer">
  <div class="line">
    Дата: <span class="blank">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
  </div>
  <div class="line">
    Подпись: <span class="blank">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
    / {full_name_short} /
  </div>
</div>

</body>
</html>
"""


def _fmt_rub(amount: Decimal | float | str) -> str:
    return f"{float(amount):,.2f}".replace(",", " ").replace(".", ",")


def _build_html(
    full_name: str,
    inn: str,
    year: int,
    total_amount: Decimal,
    receipts_count: int,
    prescriptions_count: int,
) -> str:
    ndfl = float(total_amount) * 0.13
    doc_rows_items = [
        (1, f"Реестр расходов на лекарственные препараты за {year} год — 1 экз."),
        (2, f"Чеки (кассовые чеки) из аптек — {receipts_count} шт."),
    ]
    if prescriptions_count > 0:
        doc_rows_items.append(
            (3, f"Рецепты, оформленные в установленном порядке — {prescriptions_count} шт.")
        )
    doc_rows_items.append(
        (
            len(doc_rows_items) + 1,
            "Справка из медицинского учреждения (при необходимости)",
        )
    )
    rows_html = "\n".join(
        f"<tr><td>{i}.</td><td>{text}</td></tr>" for i, text in doc_rows_items
    )

    # Short name: "Иванов И.И."
    parts = full_name.split()
    if len(parts) >= 2:
        short = parts[0] + " " + " ".join(p[0] + "." for p in parts[1:])
    else:
        short = full_name

    return _HTML_TEMPLATE.format(
        full_name=full_name or "___________________",
        inn=inn or "___________________",
        year=year,
        total_amount=_fmt_rub(total_amount),
        ndfl_return=_fmt_rub(ndfl),
        doc_rows=rows_html,
        full_name_short=short or "___________________",
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def generate_cover_letter(
    user: Any,
    year: int,
    summary: dict[str, Any],
    db: Any,
) -> bytes:
    """Generate cover letter PDF bytes.

    Args:
        user: User ORM model (may have decrypted full_name, inn fields)
        year: Tax year
        summary: dict with keys total_amount, months (list)
        db: AsyncSession (unused currently, reserved for future queries)

    Returns:
        PDF bytes

    Raises:
        RuntimeError if neither WeasyPrint nor ReportLab is available
    """
    # Extract fields from user (may be None / encrypted placeholder)
    full_name: str = getattr(user, "full_name", "") or ""
    inn: str = getattr(user, "inn", "") or ""

    total_amount = Decimal(str(summary.get("total_amount", "0")))
    months = summary.get("months", [])
    receipts_count = sum(int(m.get("receipts_count", 0)) for m in months)

    # Count prescriptions (approximate from summary)
    prescriptions_count: int = summary.get("prescriptions_count", 0)

    html = _build_html(full_name, inn, year, total_amount, receipts_count, prescriptions_count)

    if _HAS_WEASYPRINT:
        pdf_bytes: bytes = _WP_HTML(string=html).write_pdf()
        logger.debug("Cover letter generated via WeasyPrint (%d bytes)", len(pdf_bytes))
        return pdf_bytes

    if _HAS_REPORTLAB:
        return _reportlab_fallback(full_name, inn, year, total_amount, receipts_count)

    raise RuntimeError("Neither WeasyPrint nor ReportLab is installed")


def _reportlab_fallback(
    full_name: str,
    inn: str,
    year: int,
    total_amount: Decimal,
    receipts_count: int,
) -> bytes:
    """Minimal ReportLab-based cover letter when WeasyPrint is unavailable."""
    import os

    buf = _io.BytesIO()
    # Try to register Cyrillic font
    font_name = "Helvetica"
    try:
        import reportlab

        rl_dir = os.path.dirname(reportlab.__file__)
        font_path = os.path.join(rl_dir, "fonts", "DejaVuSans.ttf")
        if os.path.exists(font_path):
            _pdfmetrics.registerFont(_TTFont("DejaVuSans", font_path))
            font_name = "DejaVuSans"
    except Exception:
        pass

    doc = _Doc(
        buf,
        pagesize=_A4,
        leftMargin=3 * _cm,
        rightMargin=2.5 * _cm,
        topMargin=2 * _cm,
        bottomMargin=2 * _cm,
        title=f"Заявление на вычет {year}",
    )
    styles = _get_styles()
    normal = styles["Normal"]
    normal.fontName = font_name
    normal.fontSize = 11
    normal.leading = 16

    ndfl = round(float(total_amount) * 0.13, 2)
    story = [
        _Para(f"<b>Заявление о налоговом вычете {year} года</b>", normal),
        _Spacer(1, 0.5 * _cm),
        _Para(f"ФИО: {full_name or '___________'}", normal),
        _Para(f"ИНН: {inn or '___________'}", normal),
        _Spacer(1, 0.5 * _cm),
        _Para(
            f"Прошу предоставить социальный налоговый вычет (ст. 219 НК РФ) "
            f"по расходам на лекарства за {year} год.",
            normal,
        ),
        _Spacer(1, 0.3 * _cm),
        _Para(f"Сумма расходов: {_fmt_rub(total_amount)} руб.", normal),
        _Para(f"Возврат НДФЛ (13%): {_fmt_rub(ndfl)} руб.", normal),
        _Spacer(1, 0.3 * _cm),
        _Para(f"Приложения: {receipts_count} чеков, реестр расходов.", normal),
        _Spacer(1, 1 * _cm),
        _Para("Дата: ___________  Подпись: ___________", normal),
    ]
    doc.build(story)
    return buf.getvalue()
