"""ZIP Packager (H-01).

Creates an in-memory ZIP archive containing:
  - PDF registry (generated by pdf_registry.py)
  - Original receipt files downloaded from S3
  - Prescription photos (if any)

The ZIP is then uploaded to S3 bucket medvychet-exports with TTL 7 days.
"""
from __future__ import annotations

import io
import logging
import uuid
import zipfile
from datetime import date

logger = logging.getLogger(__name__)

BUCKET_EXPORTS = "medvychet-exports"


async def build_zip(user_id: uuid.UUID, year: int, db) -> bytes:
    """Build a ZIP archive for the user's tax deduction documents.

    Args:
        user_id: UUID of the user
        year: calendar year for the export
        db: async SQLAlchemy session

    Returns:
        ZIP as bytes
    """
    from app.services.export import pdf_registry as _pdf_reg
    from app.services.storage.s3_client import BUCKET_RECEIPTS, S3Client
    generate_registry = _pdf_reg.generate_registry

    s3 = S3Client()
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # 1. PDF registry
        try:
            pdf_bytes = await generate_registry(user_id, year, db)
            zf.writestr(f"rejestr_{year}.pdf", pdf_bytes)
            logger.debug("Added PDF registry (%d bytes)", len(pdf_bytes))
        except Exception as exc:
            logger.error("Failed to generate PDF registry: %s", exc)

        # 2. Original receipt files
        receipts = await _fetch_receipts(user_id, year, db)
        for receipt in receipts:
            try:
                obj = s3.get_object(BUCKET_RECEIPTS, receipt.s3_key)
                file_bytes: bytes = obj["Body"].read()
                ext = receipt.s3_key.rsplit(".", 1)[-1] if "." in receipt.s3_key else "jpg"
                filename = f"receipts/{_safe_date(receipt.purchase_date)}_{receipt.id}.{ext}"
                zf.writestr(filename, file_bytes)
            except Exception as exc:
                logger.warning("Failed to add receipt %s: %s", receipt.id, exc)

        # 3. Prescription photos
        prescriptions = await _fetch_prescriptions(user_id, year, db)
        for presc in prescriptions:
            if not presc.s3_key:
                continue
            try:
                obj = s3.get_object(BUCKET_RECEIPTS, presc.s3_key)
                file_bytes = obj["Body"].read()
                ext = presc.s3_key.rsplit(".", 1)[-1] if "." in presc.s3_key else "jpg"
                filename = f"prescriptions/{presc.issue_date}_{presc.id}.{ext}"
                zf.writestr(filename, file_bytes)
            except Exception as exc:
                logger.warning("Failed to add prescription %s: %s", presc.id, exc)

    buf.seek(0)
    return buf.read()


async def upload_zip(user_id: uuid.UUID, year: int, zip_bytes: bytes) -> str:
    """Upload ZIP to S3 and return the S3 key.

    Args:
        user_id: UUID of the user
        year: calendar year
        zip_bytes: ZIP content

    Returns:
        S3 key of the uploaded file
    """
    from app.services.storage.s3_client import S3Client

    export_id = uuid.uuid4()
    s3_key = f"{user_id}/{year}_{export_id}.zip"
    s3 = S3Client()
    s3.upload_file(
        BUCKET_EXPORTS,
        s3_key,
        zip_bytes,
        "application/zip",
    )
    logger.info("ZIP uploaded to %s/%s (%d bytes)", BUCKET_EXPORTS, s3_key, len(zip_bytes))
    return s3_key


def _safe_date(d: date | None) -> str:
    return d.strftime("%Y-%m-%d") if d else "unknown"


async def _fetch_receipts(user_id: uuid.UUID, year: int, db):
    from sqlalchemy import extract, select
    from app.models.enums import OCRStatus
    from app.models.receipt import Receipt

    result = await db.execute(
        select(Receipt).where(
            Receipt.user_id == user_id,
            extract("year", Receipt.created_at) == year,
            Receipt.ocr_status.in_([OCRStatus.DONE, OCRStatus.REVIEW]),
        )
    )
    return result.scalars().all()


async def _fetch_prescriptions(user_id: uuid.UUID, year: int, db):
    from sqlalchemy import extract, select
    from app.models.prescription import Prescription

    result = await db.execute(
        select(Prescription).where(
            Prescription.user_id == user_id,
            extract("year", Prescription.created_at) == year,
            Prescription.status != "deleted",
            Prescription.s3_key.isnot(None),
        )
    )
    return result.scalars().all()
